-- ============================================
-- [초기화] 기존 테이블 및 데이터 깨끗하게 삭제 (재구축용)
-- ============================================
DROP TABLE IF EXISTS public.analysis_logs CASCADE;
DROP TABLE IF EXISTS public.exercises CASCADE; 
DROP TABLE IF EXISTS public.users CASCADE;

-- ============================================
-- 1. 사용자 테이블 (회원 관리)
-- ============================================
CREATE TABLE IF NOT EXISTS public.users (
    id UUID REFERENCES auth.users(id) NOT NULL PRIMARY KEY,
    email TEXT,
    nickname TEXT,
    role TEXT CHECK (role IN ('USER', 'ADMIN')) DEFAULT 'USER',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================
-- 2. 분석 기록 테이블 (InBody 스타일 분석 및 타겟 설정 포함)
-- ============================================
CREATE TABLE IF NOT EXISTS public.analysis_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
    
    -- 운동 이름 (예: "스쿼트", "어깨 운동")
    exercise_name TEXT NOT NULL, 
    
    -- [NEW] 분석 타겟 부위 (정확도 향상용)
    -- 영상 업로드 시 선택: 상체(UPPER), 하체(LOWER), 전신(FULL)
    target_area TEXT CHECK (target_area IN ('UPPER', 'LOWER', 'FULL')) DEFAULT 'FULL',

    -- [NEW] 운동 방식 타입 (생체역학적 특성)
    -- 등장성(ISOTONIC), 등척성(ISOMETRIC), 등속성(ISOKINETIC)
    motion_type TEXT CHECK (motion_type IN ('isotonic', 'isometric', 'isokinetic')) DEFAULT 'isotonic',

    -- [NEW] 운동 부위 (분석 최적화용)
    -- 상체(UPPER_BODY), 하체(LOWER_BODY), 전신(FULL_BODY)
    target_part TEXT CHECK (target_part IN ('upper_body', 'lower_body', 'full_body')) DEFAULT 'full_body',

    -- 영상 경로 (Supabase Storage)
    video_path TEXT NOT NULL, 
    
    -- [NEW] 레이더 차트용 데이터 (비교 분석용)
    -- InBody 스타일 시각화를 위한 5~6각형 점수 (예: 근력, 유연성, 일관성 등)
    -- 데이터 예시: {"balance": 80, "strength": 70, "stability": 90}
    radar_data JSONB DEFAULT '{}'::jsonb,

    -- ★ 핵심: 8대 관절 및 근육 상세 분석 결과 (JSONB)
    -- 기존의 상세 관절 데이터 및 근육 활성도 저장
    -- 예: {"muscle_usage": {"quadriceps": 70, "glutes": 30}, "joint_angles": {...}}
    analysis_result JSONB, 
    
    -- [NEW] 생체역학 분석 결과 (JSONB 리스트 형식)
    -- 주동근/안정근 분류 및 역할 정보 포함
    -- 예: [{"part": "Shoulder", "score": 85, "role": "PRIME_MOVER", "comment": "Active flexion"}]
    analysis_json JSONB, 
    
    -- [NEW] 등척성 운동용 초기 중력 벡터 (Float Array: [x, y, z])
    -- ISOMETRIC 운동 시 초기 자세의 중력 벡터를 저장하여 안정성 측정에 사용
    reference_gravity FLOAT[],
    
    -- [NEW] 원본 측정 데이터 (JSONB)
    -- 각 운동 타입별 Raw Data 저장 (ROM, 각속도, 중력 편차 등)
    analysis_raw_data JSONB,
    
    -- 상태 (분석 완료 시 COMPLETED로 변경)
    status TEXT CHECK (status IN ('UPLOADING', 'PROCESSING', 'COMPLETED', 'FAILED')) DEFAULT 'UPLOADING',
    
    -- 영상 메타데이터
    video_duration_seconds FLOAT, 
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 인덱스 설정 (검색 및 정렬 속도 향상)
CREATE INDEX IF NOT EXISTS idx_analysis_logs_user_id ON public.analysis_logs(user_id);
CREATE INDEX IF NOT EXISTS idx_analysis_logs_created_at ON public.analysis_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analysis_logs_target_area ON public.analysis_logs(target_area); -- 타겟별 필터링을 위해 추가
CREATE INDEX IF NOT EXISTS idx_analysis_logs_motion_type ON public.analysis_logs(motion_type); -- 운동 방식별 필터링을 위해 추가

-- ============================================
-- 3. 보안 정책 (RLS) - 내 데이터는 나만 관리
-- ============================================
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analysis_logs ENABLE ROW LEVEL SECURITY;

-- Users 정책
CREATE POLICY "Users can view own profile" ON public.users FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.users FOR UPDATE USING (auth.uid() = id);

-- Analysis Logs 정책
CREATE POLICY "Users can view own logs" ON public.analysis_logs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own logs" ON public.analysis_logs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update own logs" ON public.analysis_logs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete own logs" ON public.analysis_logs FOR DELETE USING (auth.uid() = user_id);

-- ============================================
-- 4. 필수 트리거 (자동 처리 기능)
-- ============================================

-- 사용자 자동 생성 함수 (회원가입 시 실행)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.users (id, email, nickname)
    VALUES (NEW.id, NEW.email, COALESCE(NEW.raw_user_meta_data->>'nickname', NEW.email));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Auth 트리거 연결
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 업데이트 시간(updated_at) 자동 갱신 함수
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Analysis Logs 업데이트 트리거 연결
DROP TRIGGER IF EXISTS update_analysis_logs_updated_at ON public.analysis_logs;
CREATE TRIGGER update_analysis_logs_updated_at
    BEFORE UPDATE ON public.analysis_logs
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
    -- ============================================
    -- 1. 깔끔한 시작을 위해 기존 videos 테이블이 있다면 삭제합니다.
DROP TABLE IF EXISTS videos;

-- 2. 새로운 구조로 videos 테이블을 생성합니다.
CREATE TABLE videos (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL, -- 사용자 ID
    
    video_url TEXT NOT NULL,       -- 영상 저장 경로
    thumbnail_url TEXT,            -- 썸네일 이미지 경로
    
    -- ⭐️ 수정된 부분: 띄어쓰기 오류 해결 & 날짜 포맷 적용
    video_title TEXT DEFAULT to_char(now(), 'YYYY-MM-DD "운동 기록"'),
    
    -- ⭐️ 새로 추가된 타겟 부위 컬럼 (상체, 하체, 전신 제한)
    target_area TEXT CHECK (target_area IN ('UPPER', 'LOWER', 'FULL')),
    
    analysis_result JSONB,         -- Gemini 분석 결과 저장소
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 보안 설정 (RLS) 활성화
ALTER TABLE videos ENABLE ROW LEVEL SECURITY;

-- 4. 내 데이터만 볼 수 있게 설정 (SELECT)
CREATE POLICY "Enable read access for own videos" 
ON videos FOR SELECT 
USING (auth.uid() = user_id);

-- 5. 내 데이터를 추가할 수 있게 설정 (INSERT)
CREATE POLICY "Enable insert access for own videos" 
ON videos FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 6. 내 데이터를 삭제할 수 있게 설정 (DELETE)
CREATE POLICY "Enable delete access for own videos" 
ON videos FOR DELETE 
USING (auth.uid() = user_id);

-- 7. 내 데이터를 수정할 수 있게 설정 (UPDATE)
CREATE POLICY "Enable update access for own videos" 
ON videos FOR UPDATE 
USING (auth.uid() = user_id);